<?php
include('dbconnection/connection.php');
 $name1=$_GET['cord'];
  $name2=$_GET['supr'];
   $qot=$_GET['qot']; 
//$k="select email from registrations where name='$name1'";
//$q1=mysqli_query($link,$k) or die(mysqli_error($link));
//while($r1=mysqli_fetch_array($q1)){
   // $to = "ospshyd@yahoo.com".",";
  // $to = $r1['email'].",";
 //}
// $k1="select email from registrations where name='$name2'";
//$q11=mysqli_query($link,$k1) or die(mysqli_error($link));
//while($r2=mysqli_fetch_array($q11)){
   // $to = "ospshyd@yahoo.com".",";
  // $to.= $r2['email'];
 //}
// $to; 
//$to = "sam241997@gmail.com";
//$to="koti.kolagani@gmail.com";
//$from = "Jyothi AP Quotations <koti.kolagani@gmail.com>";

$from=$name1;
$x="jyothi.infraservices@gmail.com";
$subject = "Jyothi KL Quotations with attachment";

$to = "$name1".",";
$to.= $name2;
$to.= $x;

$separator = md5(time());

// carriage return type (we use a PHP end of line constant)
$eol = PHP_EOL;

// attachment namezz

 $filename = "KL-$qot.pdf"; 


//$pdfdoc is PDF generated by FPDF
$pdfdoc     = 'demo.pdf';
$pdfdoc=file_get_contents('demo.pdf');

$attachment = chunk_split(base64_encode($pdfdoc));

// main header
$headers  = "From: ".$from.$eol;
$headers .= "MIME-Version: 1.0".$eol; 
$headers .= "Content-Type: multipart/mixed; boundary=\"".$separator."\"";

// no more headers after this, we start the body! //

$message = "This is system generated email do not reply.";
$body = "--".$separator.$eol;
$body .= "Content-Transfer-Encoding: 7bit".$eol.$eol;
$body .= "This is a TG Quotation Number : $qot .".$eol;

// message
$body .= "--".$separator.$eol;
$body .= "Content-Type: text/html; charset=\"iso-8859-1\"".$eol;
$body .= "Content-Transfer-Encoding: 8bit".$eol.$eol;
$body .= $message.$eol;

// attachment
$body .= "--".$separator.$eol;
$body .= "Content-Type: application/pdf; name=\"".$filename."\"".$eol; 
$body .= "Content-Transfer-Encoding: base64".$eol;
$body .= "Content-Disposition: attachment".$eol.$eol;
$body .= $attachment.$eol;
$body .= "--".$separator."--";

// send message
if (mail($to, $subject, $body, $headers)) {
    echo '<script language="javascript">';
echo 'alert("mail successfully sent")';
echo '</script>';
	print "<script>";
	print "self.location='klqot_list.php';";
	print "</script>";
} else {
echo "mail send ... ERROR";
}

?>